//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_WEB.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KN_BDEntities : DbContext
    {
        public KN_BDEntities()
            : base("name=KN_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbError> tbError { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
    
        public virtual ObjectResult<spIniciarSesion_Result> spIniciarSesion(string correoElectronico, string contrasenna)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spIniciarSesion_Result>("spIniciarSesion", correoElectronicoParameter, contrasennaParameter);
        }
    
        public virtual int spRegistrarError(string mensaje, Nullable<System.DateTime> fechaHora, string lugar, Nullable<int> consecutivoUsuario)
        {
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("Mensaje", mensaje) :
                new ObjectParameter("Mensaje", typeof(string));
    
            var fechaHoraParameter = fechaHora.HasValue ?
                new ObjectParameter("FechaHora", fechaHora) :
                new ObjectParameter("FechaHora", typeof(System.DateTime));
    
            var lugarParameter = lugar != null ?
                new ObjectParameter("Lugar", lugar) :
                new ObjectParameter("Lugar", typeof(string));
    
            var consecutivoUsuarioParameter = consecutivoUsuario.HasValue ?
                new ObjectParameter("ConsecutivoUsuario", consecutivoUsuario) :
                new ObjectParameter("ConsecutivoUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRegistrarError", mensajeParameter, fechaHoraParameter, lugarParameter, consecutivoUsuarioParameter);
        }
    
        public virtual int spRegistrarUsuario(string identificacion, string nombre, string correoElectronico, string contrasenna)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRegistrarUsuario", identificacionParameter, nombreParameter, correoElectronicoParameter, contrasennaParameter);
        }
    }
}
