//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_WEB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbError
    {
        public int Consecutivo { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Lugar { get; set; }
        public int ConsecutivoUsuario { get; set; }
    }
}
