//------------------------------------------------------------------------------
// <auto-generated>
//     Código generado manualmente a partir de Model1.edmx (Database First).
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2.Web.EF
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Practica2Entities : DbContext
    {
        public Practica2Entities()
            : base("name=Practica2Entities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Mascotas> Mascotas { get; set; }
    }
}
