//------------------------------------------------------------------------------
// <auto-generated>
//     Código generado manualmente a partir de Model1.edmx (Database First).
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2.Web.EF
{
    using System;

    public partial class tbError
    {
        public int Consecutivo { get; set; }
        public DateTime Fecha { get; set; }
        public string Mensaje { get; set; }
        public string Lugar { get; set; }
        public int Usuario { get; set; }
    }
}
